version: '2.4'
services:
  wordpress:
    build: .
    hostname: wordpress
    networks:
      - dmz
    cpu_count: 1
    cpu_percent: 50
    mem_limit: 1024m
    ports:
      - "80:80"
    depends_on:
      - dbserver
    
  dbserver:
    image: mysql:5.7
    networks:
      - dmz
    cpu_count: 1
    cpu_percent: 50
    environment:
      MYSQL_ROOT_PASSWORD: 4linux
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpressuser
      MYSQL_PASSWORD: 4linux
    restart: always
    volumes:
      - "treta:/var/lib/mysql"

volumes:
  treta:
    external: true
networks:
  dmz:
    driver: bridge

